remote_theme: jekyll/minima

title: The Foxhole
author:
  name: Summit Sarkar
  email: contact@summitsarkar.com
description: >
  So literate
minima:
  date_format: "%b %-d, %Y"
show_excerpts: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
