# Settings
baseURL = "https://cgm616.me/"
languageCode = "en-US" # or en-US
title = "cgm616"
description = "Cole's personal website"
theme = ["hugo-redirect", "basic"]
canonifyURLs = true
copyright = "Cole Graber-Mitchell"
enableRobotsTXT = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
    unsafe = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"