# Settings
baseURL = "https://summitsarkar.com/"
languageCode = "en-US" # or en-US
title = "summitsarkar.com"
description = "Summit's personal website"
theme = ["hugo-redirect", "basic"]
canonifyURLs = true
copyright = "Summit Sarkar"
enableRobotsTXT = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
    unsafe = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"
